name: codeit
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  curved_navigation_bar:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true
  assets:
    - images/appstore.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf


  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

